---
# Overwrite any of the roles variables here
# Mostly can be found under the role's default folder in the main.yml ( or any yml in there )

user: vagrant


# For the role server_banners_prompts
# Systemd Services to be shown on the MOTD for their status
services:
  - sshd
  - systemd-timesyncd
  - docker
  - code-server
  - vncserver@:0
  - vncserver@:1
  - novnc@0
  - novnc@1

# For the rol zsh
# choose yours from https://zshthem.es/all/
oh_my_zsh_theme: fletcherm
users:
  - username: vagrant
  - username: root

extra_zshrc_config:  |
    source $HOME/.asdf/asdf.sh

# For the role awscli
asdf_version: v0.6.2
asdf_user: vagrant
asdf_plugins:
  - name: "terraform"
    versions: ["0.12.0", "0.13.0", "0.14.0"]
    global: "0.14.0"
  - name: "packer"
    versions: ["1.7.1"]
    global: "1.7.1"
  - name: "kubectl"
    versions: ["1.17.0","1.18.0", "1.19.0", "1.20.0"]
    global: "1.17.0"

# For the role Python
# Specify names, versions and state
pip_package: python-pip 

pip_install_packages:
  - name: setuptools_rust
    version: "0.12.1"
    state: present
  - name: ansible
    version: "3.2.0"
    state: present
  - name: docker_py
    version: "1.10.6"
    state: present
  # - name: molecule
  # - name: molecule-vagrant
  # - name: molecule-docker

# For the role apps
apps:
  - git
  - vim
  - nano
  - tmux
  - jq
  - vagrant
  - virtualbox
  - firefox
  - openvpn
  - fakeroot
  - nmap
  - nikto
  - terminator
  - gobuster
  - metasploit
  - exploit-db

# For the role code-server
deploy_code_server: true # default is false
code_server_user_data_path: "/home/vagrant/sync_folder"


# For the VNC role
tigervnc_user: vagrant
tigervnc_vncpass: vagrant
tigervnc_user_home: "/home/{{ tigervnc_user }}"

# For the docker role
docker_users: ['vagrant']
docker_images_pull: true
docker_images:
  - alpine
  - amazonlinux
  - ansible/awx
  - aquasec/kube-hunter
  - aquasec/trivy
  - bash
  - bash:5.0.18
  - busybox
  - centos
  - centos:centos7
  - centos:centos8
  - concourse/concourse
  - diverdane/secretless-k8s-demo
  - elasticsearch:7.9.1
  - fedora:29
  - fedora:30
  - fedora:31
  - jekyll/jekyll
  - kalilinux/kali
  - kalilinux/kali-rolling
  - kibana:7.9.1
  - mariadb
  - mysql
  - postgres
  - python
  - python:3.9.0rc1-buster
  - rmountjoy/dashmachine
  - ubuntu:18.04
  - chentex/random-logger:latest

# For the role YAY
yay_role_apps: 
  - visual-studio-code-bin
  - zenmap
